[package]
name = "Tachiyomi-TUI"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.30.0"
ratatui-image = "10.0.2"
reqwest = "0.13.1"
sqlx = "0.8.6"
tokio = "1.49.0"
